# Generated by Django 3.0.5 on 2020-05-03 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mode_of_payments', '0002_auto_20200503_0907'),
        ('bookings', '0004_auto_20200503_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('customer_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mode_of_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mode_of_payments.ModeOfPayment')),
                ('payment_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Booking')),
            ],
            options={
                'db_table': 'tbl_Payments',
            },
        ),
    ]
