# Generated by Django 3.0.5 on 2020-04-29 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelRoutes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('origin', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('price', models.IntegerField()),
                ('bus_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buses.Bus')),
            ],
            options={
                'db_table': 'tbl_TravelRoutes',
            },
        ),
    ]
