# Generated by Django 3.0.5 on 2020-04-29 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelroutes',
            name='date_of_travel',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='travelroutes',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='travelroutes',
            name='time_of_departure',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
