# Generated by Django 3.0.5 on 2020-04-29 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("buses", "0002_auto_20200429_1119"),
        ("travel_routes", "0003_auto_20200429_1144"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TravelRoutes",
            new_name="TravelRoute",
        ),
    ]
