# Generated by Django 3.0.5 on 2020-04-29 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("buses", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="bus",
            table="tbl_Bus",
        ),
    ]
