# Generated by Django 3.0.5 on 2020-05-03 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("buses", "0002_auto_20200429_1119"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bus",
            options={"verbose_name_plural": "Buses"},
        ),
    ]
