# Generated by Django 3.0.5 on 2020-05-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModeOfPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_of_payment', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tbl_Mode_Of_Payment',
            },
        ),
    ]
