# Generated by Django 3.0.5 on 2020-05-03 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mode_of_payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="modeofpayment",
            options={"verbose_name": "Mode Of Payment"},
        ),
    ]
