# Generated by Django 3.0.5 on 2020-04-29 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='booking',
            table='tbl_Bookings',
        ),
    ]
