# Generated by Django 3.0.5 on 2020-04-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20200430_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amount_paid',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
