# Generated by Django 3.0.5 on 2020-05-03 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mode_of_payments', '0002_auto_20200503_0907'),
        ('bookings', '0004_auto_20200503_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='mode_of_payment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mode_of_payments.ModeOfPayment'),
        ),
    ]
