# Generated by Django 3.0.5 on 2020-05-03 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0005_booking_mode_of_payment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="amount_paid",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="mode_of_payment",
        ),
    ]
